// <auto-generated />
using System;
using FastxWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastxWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809170748_Ro")]
    partial class Ro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateTime(2025, 8, 8, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9343),
                            IsDeleted = true,
                            NoOfSeats = 1,
                            RouteId = 1,
                            Status = "Cancelled",
                            TotalFare = 1500.00m,
                            UserId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateTime(2025, 8, 8, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9355),
                            IsDeleted = false,
                            NoOfSeats = 2,
                            RouteId = 2,
                            Status = "Booked",
                            TotalFare = 1600.00m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.BookingSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingsSeats", (string)null);
                });

            modelBuilder.Entity("FastxWebApi.Models.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusOperatorId")
                        .HasColumnType("int");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.HasIndex("BusOperatorId");

                    b.ToTable("Buses", (string)null);

                    b.HasData(
                        new
                        {
                            BusId = 1,
                            Amenities = "Wi-Fi, Water Bottle,TV",
                            BusName = "Volvo",
                            BusNumber = "KA-01-AB-8754",
                            BusType = "AC Sleeper",
                            IsDeleted = false,
                            Status = "Active",
                            TotalSeats = 40
                        },
                        new
                        {
                            BusId = 2,
                            Amenities = "Wi-Fi",
                            BusName = "BENZ",
                            BusNumber = "TN-02-CD-9999",
                            BusType = "Non-AC",
                            IsDeleted = false,
                            Status = "Active",
                            TotalSeats = 45
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FastxWebApi.Models.Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefundId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ProcessedBy");

                    b.HasIndex("UserId");

                    b.ToTable("Refunds");

                    b.HasData(
                        new
                        {
                            RefundId = 1,
                            BookingId = 1,
                            RefundAmount = 1500.00m,
                            RefundDate = new DateTime(2025, 8, 9, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9390),
                            Status = "Pending",
                            UserId = 1
                        },
                        new
                        {
                            RefundId = 2,
                            BookingId = 2,
                            ProcessedBy = 2,
                            RefundAmount = 800.00m,
                            RefundDate = new DateTime(2025, 8, 9, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9395),
                            Status = "Approved",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Bus Operator"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.HasIndex("BusId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            ArrivalTime = new DateTime(2025, 8, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 1,
                            DepartureTime = new DateTime(2025, 8, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Chidambaram",
                            Fare = 1500.00m,
                            IsDeleted = false,
                            Origin = "Bangalore",
                            Status = "Active"
                        },
                        new
                        {
                            RouteId = 2,
                            ArrivalTime = new DateTime(2025, 8, 3, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            BusId = 2,
                            DepartureTime = new DateTime(2025, 8, 2, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Cuddalore",
                            Fare = 800.00m,
                            IsDeleted = false,
                            Origin = "Chennai",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("RouteId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            IsBooked = false,
                            IsDeleted = false,
                            RouteId = 1,
                            SeatNumber = "A1",
                            Status = "Active"
                        },
                        new
                        {
                            SeatId = 2,
                            IsBooked = false,
                            IsDeleted = false,
                            RouteId = 1,
                            SeatNumber = "A2",
                            Status = "Active"
                        },
                        new
                        {
                            SeatId = 3,
                            IsBooked = false,
                            IsDeleted = false,
                            RouteId = 1,
                            SeatNumber = "B1",
                            Status = "Active"
                        },
                        new
                        {
                            SeatId = 4,
                            IsBooked = false,
                            IsDeleted = false,
                            RouteId = 2,
                            SeatNumber = "C1",
                            Status = "Active"
                        },
                        new
                        {
                            SeatId = 5,
                            IsBooked = false,
                            IsDeleted = false,
                            RouteId = 2,
                            SeatNumber = "C2",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HashKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "CDM",
                            ContactNumber = "9876543210",
                            CreatedAt = new DateTime(2025, 8, 9, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(8969),
                            Email = "Nimal@fastx.com",
                            Gender = "Male",
                            HashKey = new byte[] { 217, 197, 204, 209, 254, 114, 74, 182, 104, 164, 250, 113, 152, 66, 171, 99, 26, 199, 70, 223, 129, 102, 185, 137, 148, 100, 143, 77, 159, 127, 129, 67, 227, 245, 10, 250, 94, 138, 203, 253, 25, 94, 45, 144, 36, 160, 114, 193, 220, 130, 228, 248, 148, 139, 83, 166, 25, 33, 115, 63, 78, 12, 3, 157 },
                            IsDeleted = false,
                            Name = "Nimalan",
                            Password = new byte[] { 157, 84, 42, 68, 91, 49, 212, 41, 144, 150, 251, 81, 124, 247, 137, 52, 51, 96, 96, 147, 155, 164, 209, 1, 157, 147, 61, 118, 167, 187, 109, 77 },
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "LA, california",
                            ContactNumber = "785423654",
                            CreatedAt = new DateTime(2025, 8, 9, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9009),
                            Email = "GM@fastx.com",
                            Gender = "Male",
                            HashKey = new byte[] { 247, 183, 243, 104, 230, 167, 98, 210, 61, 65, 107, 79, 247, 41, 147, 221, 116, 181, 0, 7, 157, 6, 151, 139, 196, 27, 57, 107, 104, 74, 243, 82, 146, 77, 201, 230, 18, 191, 108, 54, 31, 138, 3, 134, 24, 247, 242, 104, 121, 86, 162, 227, 204, 222, 13, 109, 164, 93, 242, 165, 195, 111, 245, 245 },
                            IsDeleted = false,
                            Name = "Guru",
                            Password = new byte[] { 119, 109, 90, 71, 35, 232, 249, 8, 166, 176, 104, 104, 224, 111, 82, 14, 128, 25, 223, 69, 142, 207, 252, 166, 247, 97, 241, 18, 105, 166, 2, 62 },
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Heaven block 1",
                            BusId = 1,
                            ContactNumber = "4552155741",
                            CreatedAt = new DateTime(2025, 8, 9, 22, 37, 47, 706, DateTimeKind.Local).AddTicks(9104),
                            Email = "thordriver@fastx.com",
                            Gender = "Male",
                            HashKey = new byte[] { 217, 116, 147, 42, 12, 188, 141, 255, 83, 47, 229, 0, 110, 185, 138, 239, 134, 49, 199, 241, 205, 250, 198, 87, 150, 235, 204, 190, 235, 13, 167, 71, 11, 200, 221, 130, 110, 13, 236, 152, 86, 175, 181, 212, 67, 234, 147, 241, 102, 133, 153, 152, 103, 241, 246, 164, 180, 10, 48, 198, 98, 9, 134, 87 },
                            IsDeleted = false,
                            Name = "Driver Thor",
                            Password = new byte[] { 94, 60, 11, 97, 177, 0, 150, 103, 250, 190, 130, 190, 153, 67, 156, 131, 178, 245, 82, 229, 44, 56, 235, 24, 16, 208, 38, 27, 57, 176, 124, 200 },
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.HasOne("FastxWebApi.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.BookingSeat", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("FastxWebApi.Models.Bus", b =>
                {
                    b.HasOne("FastxWebApi.Models.User", "BusOperator")
                        .WithMany("Buses")
                        .HasForeignKey("BusOperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BusOperator");
                });

            modelBuilder.Entity("FastxWebApi.Models.Payment", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("FastxWebApi.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.Refund", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithOne("Refund")
                        .HasForeignKey("FastxWebApi.Models.Refund", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.User", "ProcessedByUser")
                        .WithMany("ProcessedRefunds")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastxWebApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ProcessedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.HasOne("FastxWebApi.Models.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.HasOne("FastxWebApi.Models.Route", "Route")
                        .WithMany("Seats")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.HasOne("FastxWebApi.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Payment");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("FastxWebApi.Models.Bus", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("FastxWebApi.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Buses");

                    b.Navigation("ProcessedRefunds");
                });
#pragma warning restore 612, 618
        }
    }
}
