// <auto-generated />
using System;
using FastxWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastxWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250802054952_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NoOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FastxWebApi.Models.BookingSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingsSeats");
                });

            modelBuilder.Entity("FastxWebApi.Models.Bus", b =>
                {
                    b.Property<int>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("BusId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = 1,
                            Amenities = "Wi-Fi, Water Bottle,TV",
                            BusName = "Volvo ",
                            BusNumber = "KA-01-AB-8754",
                            BusType = "AC Sleeper",
                            TotalSeats = 40
                        },
                        new
                        {
                            BusId = 2,
                            Amenities = "Wi-Fi",
                            BusName = "BENZ  ",
                            BusNumber = "TN-02-CD-9999",
                            BusType = "Non-AC",
                            TotalSeats = 45
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("FastxWebApi.Models.Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefundId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("ProcessedBy");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("FastxWebApi.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Bus Operator"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RouteId");

                    b.HasIndex("BusId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = 1,
                            ArrivalTime = new DateTime(2025, 8, 3, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            BusId = 1,
                            DepartureTime = new DateTime(2025, 8, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Chidambaram",
                            Fare = 1500.00m,
                            Origin = "Bangalore"
                        },
                        new
                        {
                            RouteId = 2,
                            ArrivalTime = new DateTime(2025, 8, 3, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            BusId = 2,
                            DepartureTime = new DateTime(2025, 8, 2, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Cuddalore",
                            Fare = 800.00m,
                            Origin = "Chennai"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("RouteId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            RouteId = 1,
                            SeatNumber = "A1"
                        },
                        new
                        {
                            SeatId = 2,
                            RouteId = 1,
                            SeatNumber = "A2"
                        },
                        new
                        {
                            SeatId = 3,
                            RouteId = 1,
                            SeatNumber = "B1"
                        },
                        new
                        {
                            SeatId = 4,
                            RouteId = 2,
                            SeatNumber = "C1"
                        },
                        new
                        {
                            SeatId = 5,
                            RouteId = 2,
                            SeatNumber = "C2"
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("BusId")
                        .IsUnique()
                        .HasFilter("[BusId] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "CDM",
                            ContactNumber = "9876543210",
                            CreatedAt = new DateTime(2025, 8, 2, 11, 19, 52, 57, DateTimeKind.Local).AddTicks(9909),
                            Email = "Nimal@fastx.com",
                            Gender = "Male",
                            Name = "Nimalan",
                            Password = "SayMyName",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "LA,california",
                            ContactNumber = "785423654",
                            CreatedAt = new DateTime(2025, 8, 2, 11, 19, 52, 57, DateTimeKind.Local).AddTicks(9913),
                            Email = "GM@fastx.com",
                            Gender = "Male",
                            Name = "Guru",
                            Password = "GuruHere",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Heaven block 1",
                            BusId = 1,
                            ContactNumber = "4552155741",
                            CreatedAt = new DateTime(2025, 8, 2, 11, 19, 52, 57, DateTimeKind.Local).AddTicks(9917),
                            Email = "thordriver@fastx.com",
                            Gender = "Male",
                            Name = "Driver Thor",
                            Password = "Braceforimpact",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.HasOne("FastxWebApi.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.BookingSeat", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("FastxWebApi.Models.Payment", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("FastxWebApi.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("FastxWebApi.Models.Refund", b =>
                {
                    b.HasOne("FastxWebApi.Models.Booking", "Booking")
                        .WithOne("Refund")
                        .HasForeignKey("FastxWebApi.Models.Refund", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastxWebApi.Models.User", "ProcessedByUser")
                        .WithMany("ProcessedRefunds")
                        .HasForeignKey("ProcessedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ProcessedByUser");
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.HasOne("FastxWebApi.Models.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.HasOne("FastxWebApi.Models.Route", "Route")
                        .WithMany("Seats")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.HasOne("FastxWebApi.Models.Bus", "Bus")
                        .WithOne("BusOperator")
                        .HasForeignKey("FastxWebApi.Models.User", "BusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FastxWebApi.Models.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FastxWebApi.Models.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Payment");

                    b.Navigation("Refund");
                });

            modelBuilder.Entity("FastxWebApi.Models.Bus", b =>
                {
                    b.Navigation("BusOperator");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("FastxWebApi.Models.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("FastxWebApi.Models.Route", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("FastxWebApi.Models.Seat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("FastxWebApi.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ProcessedRefunds");
                });
#pragma warning restore 612, 618
        }
    }
}
